# Generated by Django 4.2 on 2024-08-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(unique=True)),
                ('shop_name', models.CharField(max_length=20, unique=True)),
                ('shop_description', models.TextField()),
                ('shop_overall_rating', models.IntegerField(max_length=2)),
                ('shop_phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'db_shops',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('user_account', models.CharField(max_length=10, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('user_gender', models.CharField(max_length=1)),
                ('user_phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'db_users',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(unique=True)),
                ('menu_name', models.CharField(max_length=10, unique=True)),
                ('menu_overall_rating', models.IntegerField(max_length=2)),
                ('menu_price', models.IntegerField()),
                ('menu_shop', models.ForeignKey(db_column='menu_shop_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.shops', unique=True)),
            ],
            options={
                'db_table': 'db_menus',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(unique=True)),
                ('comment_text', models.TextField(unique=True)),
                ('comment_score', models.IntegerField(unique=True)),
                ('comment_menu', models.ForeignKey(db_column='comment_menu_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.menus')),
                ('comment_shop', models.ForeignKey(db_column='comment_shop_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.shops')),
                ('comment_user', models.OneToOneField(db_column='comment_user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.users')),
            ],
            options={
                'db_table': 'db_comments',
            },
        ),
    ]
