# Generated by Django 4.2 on 2024-08-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=255, null=True)),
                ('url_name', models.CharField(max_length=255, null=True)),
                ('menu_id', models.ForeignKey(db_column='menu_parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='system.menus')),
            ],
            options={
                'db_table': 'sys_menus',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('url_name', models.CharField(max_length=255, null=True, unique=True)),
                ('menu', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissions', to='system.menus')),
            ],
            options={
                'db_table': 'sys_permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_age', models.IntegerField(null=True)),
                ('role_gender', models.CharField(max_length=1, null=True)),
                ('role_phone_number', models.IntegerField(null=True)),
                ('role_menus', models.ManyToManyField(db_column='role_menus_id', db_table='sys_role_menus', to='system.menus')),
                ('role_permissions', models.ManyToManyField(db_column='role_permissions_id', db_table='sys_role_permissions', to='system.permissions')),
            ],
            options={
                'db_table': 'sys_roles',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20, unique=True)),
                ('shop_description', models.TextField()),
                ('shop_overall_rating', models.IntegerField()),
                ('shop_phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'sys_shops',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('user_account', models.CharField(max_length=10, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('user_roles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.roles')),
            ],
            options={
                'db_table': 'sys_users',
            },
        ),
        migrations.AddField(
            model_name='roles',
            name='role_shop',
            field=models.ForeignKey(db_column='role_shop_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.shops'),
        ),
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=10, unique=True)),
                ('menu_overall_rating', models.IntegerField()),
                ('menu_price', models.IntegerField()),
                ('menu_shop', models.ForeignKey(db_column='menu_shop_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.shops')),
            ],
            options={
                'db_table': 'sys_cuisines',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(unique=True)),
                ('comment_score', models.IntegerField(unique=True)),
                ('comment_menu', models.ForeignKey(db_column='comment_menu_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.cuisines')),
                ('comment_shop', models.ForeignKey(db_column='comment_shop_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.shops')),
                ('comment_user', models.OneToOneField(db_column='comment_user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.users')),
            ],
            options={
                'db_table': 'sys_comments',
            },
        ),
    ]
