# Generated by Django 4.2 on 2024-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_comments_comment_id_remove_menus_menu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
