# Generated by Django 4.2 on 2024-08-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_users_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.shops'),
        ),
    ]
